include:
    - project: 'internal/auto-devops'
      file: '/templates/auto-devops.gitlab-ci.yml'

variables:
    COMPILE_IMAGE: node:20-alpine
    COMPILE_TARGET_DIR: '.next'
    DEPLOY_AUTO: 'false'
    DOMAIN: durian.tc.app.mapboss.co.th

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/
        # - .next/cache/

compile:
    before_script:
        - cp $ENV ./
    after_script:
        - rm -rf ./.next/cache
        - ls -a
        - rm .env

    rules:
        - if: $CI_COMMIT_BRANCH == "qa"
        - when: never
    artifacts:
        paths:
            - ${COMPILE_TARGET_DIR}
    cache:
        paths:
            - .npm/
            # - .next/cache/

build:
    variables:
        DOCKERFILE_PATH: Dockerfile
    rules:
        - if: $CI_COMMIT_BRANCH == "qa"
        - when: never

deploy:
    rules:
        - if: $CI_COMMIT_BRANCH == "qa"
        - when: never

stop_deploy:
    rules:
        - if: $CI_COMMIT_BRANCH == "qa"
        - when: never
